import { Product, Review } from './types';

export const APP_NAME = "TasteLab";

// Guizhou Cuisine Mock Data
export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: '凯里红酸汤鱼底料',
    description: '贵州非遗美食代表。精选野生毛辣果（小西红柿）自然发酵，酸爽开胃，色泽红亮。无需炒制，一包料搞定正宗苗家酸汤鱼，涮火锅神器。',
    imageUrl: 'https://picsum.photos/seed/soursoup/400/300',
    tags: ['黔菜', '酸辣', '火锅底料'],
    remainingSamples: 5,
    totalSamples: 100,
    rating: 4.9,
    popularity: 99,
    spicyLevel: 3,
    sweetLevel: 1,
  },
  {
    id: '2',
    name: '遵义虾子羊肉粉',
    description: '贵州早餐之王。采用带皮黑山羊慢火熬制原汤，米粉细腻Q弹，配上糊辣椒面，鲜香而不膻。还原遵义街头的老味道，暖胃首选。',
    imageUrl: 'https://picsum.photos/seed/mutton/400/300',
    tags: ['早餐', '米粉', '老字号'],
    remainingSamples: 45,
    totalSamples: 80,
    rating: 4.8,
    popularity: 95,
    spicyLevel: 2,
    sweetLevel: 0,
  },
  {
    id: '3',
    name: '贵阳丝娃娃素春卷',
    description: '贵阳街头名小吃。手掌大的小面皮，包裹十六种切丝素菜，注入酸辣爽口的蘸水（也就是"注入灵魂"）。清爽解腻，低卡健康。',
    imageUrl: 'https://picsum.photos/seed/siwawa/400/300',
    tags: ['小吃', '素食', '低卡'],
    remainingSamples: 88,
    totalSamples: 200,
    rating: 4.6,
    popularity: 82,
    spicyLevel: 2,
    sweetLevel: 1,
  },
  {
    id: '4',
    name: '青岩古镇状元蹄',
    description: '源自青岩古镇，选用猪蹄加十余种名贵中药卤制。色泽红润，肥而不腻，软糯脱骨。满满胶原蛋白，寓意金榜题名。',
    imageUrl: 'https://picsum.photos/seed/trotter/400/300',
    tags: ['卤味', '肉食', '伴手礼'],
    remainingSamples: 0,
    totalSamples: 50,
    rating: 4.7,
    popularity: 88,
    spicyLevel: 1,
    sweetLevel: 2,
  },
  {
    id: '5',
    name: '贵州手工油辣椒',
    description: '贵州人的老干妈风味。精选花溪辣椒，人工捣碎，菜籽油爆香，加入花生碎和脆哨。拌面、拌饭、蘸水皆宜，香辣突出。',
    imageUrl: 'https://picsum.photos/seed/chili/400/300',
    tags: ['调料', '特辣', '下饭'],
    remainingSamples: 23,
    totalSamples: 150,
    rating: 4.9,
    popularity: 92,
    spicyLevel: 5,
    sweetLevel: 0,
  },
  {
    id: '6',
    name: '玫瑰红糖冰粉',
    description: '贵州夏季解暑神器。手工搓制的冰粉气泡丰富，淋上浓稠红糖水和玫瑰花酱，撒上芝麻花生。吃完火锅来一碗，瞬间解辣。',
    imageUrl: 'https://picsum.photos/seed/icejelly/400/300',
    tags: ['甜品', '解辣', '夏季'],
    remainingSamples: 60,
    totalSamples: 100,
    rating: 4.8,
    popularity: 85,
    spicyLevel: 0,
    sweetLevel: 4,
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    productId: '1',
    userName: '酸汤爱好者',
    content: '这个酸汤味道太正了！那种发酵的酸味很醇厚，不是醋能调出来的。煮鱼超级鲜！',
    rating: 5,
    date: '2023-10-15',
  },
  {
    id: 'r2',
    productId: '2',
    userName: '嗦粉大王',
    content: '羊肉片很大块，带皮的很有嚼劲。米粉要是再粗一点就更像在遵义吃的了。',
    rating: 4,
    date: '2023-10-14',
  },
  {
    id: 'r3',
    productId: '5',
    userName: '无辣不欢',
    content: '虽然很辣，但是真的香！里面还有脆哨粒，拌白米饭我能吃两碗。',
    rating: 5,
    date: '2023-10-16',
  },
  {
    id: 'r4',
    productId: '3',
    userName: '减肥达人',
    content: '丝娃娃蘸水调得很好，蔬菜都很新鲜，主要是不怕胖，很适合当晚餐。',
    rating: 5,
    date: '2023-10-12',
  },
  {
    id: 'r5',
    productId: '1',
    userName: '火锅控',
    content: '比外面饭店的酸汤锅底还要浓郁，记得加点木姜子油，味道更绝。',
    rating: 5,
    date: '2023-10-10',
  }
];